### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [aleksey-berezan/learnjs#4]
(Meets Expectations) Overall, nice work.

Remember to use new JavaScript features whenever possible, they often DRY up our code and improve the readability. Also, remember to create a helper function if you find yourself doing the same thing multiple times.

Otherwise, your code is clean and easy to follow! Great work!

**Comment by alex-berezan** [comment]
Hi CJ Jessett,
sorry for so much delayed response.
Thanks a lot for the review!
I'm marking this issue + the other ones (#1, #2, #3) as closed.

Thanks,
Alex
